### PR TITLE
Feature/issue 45/create companies page and route and link in navbar

### PR DESCRIPTION
**Pull request by LittleSweetGun**

### CODE REVIEW

**Comment by n1c01a5** [comment]
The branch name must be just `feature/create-companies-page`

**Comment by n1c01a5** [comment]
@LittleSweetGun can you share the SQL command to create the `ompanies` table.

**Comment by LittleSweetGun** [comment]
CREATE TABLE goodhive.companies (
  id SERIAL PRIMARY KEY,
  job_headline VARCHAR(255) NOT NULL,
  companies_name VARCHAR(100) NOT NULL,
  companies_address VARCHAR(100) NOT NULL,
  country VARCHAR(100) NOT NULL,
  city VARCHAR(100) NOT NULL,
  phone_country_code VARCHAR(10) NOT NULL,
  phone_number VARCHAR(20) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  telegram VARCHAR(255),
  about_work TEXT NOT NULL
);

**Comment by n1c01a5** [comment]
#45

**Review by n1c01a5 — APPROVED** [review]

**Pull request merged**
